"""Naive implementation of vehicle path tracking as an Omniverse extension."""

# pylint: disable=import-error, invalid-name, broad-except
import asyncio

import carb
import carb.settings
import omni.ext
import omni.kit
import omni.usd
from pxr import UsdGeom

from .logging import redirect_carb_logs_to_stdout
from .model import ExtensionModel
from .ui import ExtensionUI


class PathTrackingExtension(omni.ext.IExt):
    """Path Tracking Extension class"""

    def __init__(self):
        super().__init__()

        redirect_carb_logs_to_stdout()

        context = omni.usd.get_context()
        try:
            stage = context.get_stage()
        except Exception as e:
            carb.log_warn(f"Failed to get current USD stage: {e}")
            stage = None

        if stage is None:
            try:
                context.new_stage()
                stage = context.get_stage()
            except Exception as e:  # noqa: B902
                carb.log_error(f"Failed to create in-memory USD stage: {e}")
                raise
        meters_per_unit = UsdGeom.GetStageMetersPerUnit(stage)

        self.DEFAULT_LOOKAHEAD = 5.5 / meters_per_unit
        # Any user-defined changes to the lookahead parameter will be clamped:
        self.MIN_LOOKAHEAD = 4.0 / meters_per_unit
        self.MAX_LOOKAHEAD = 20.0 / meters_per_unit

        self._usd_listener = None
        self._stage_event_sub = None
        self._model = None
        self._ui = None

    def on_startup(self, ext_id):
        """Called when the extension is loaded"""
        if omni.usd.get_context().get_stage() is None:
            # Workaround for running within test environment.
            omni.usd.get_context().new_stage()

        # Usd listener could be used in the future if we could be interested
        # in recomputing changes in the vehicle planned trajectory "on the fly".
        # self._usd_listener = Tf.Notice.Register(Usd.Notice.ObjectsChanged, self._on_usd_change, None)

        self._stage_event_sub = (
            omni.usd.get_context()
            .get_stage_event_stream()
            .create_subscription_to_pop(
                self._on_stage_event, name="Stage Open/Closing Listening"
            )
        )

        self._model = ExtensionModel(
            ext_id,
            default_lookahead_distance=self.DEFAULT_LOOKAHEAD,
            max_lookahed_distance=self.MAX_LOOKAHEAD,
            min_lookahed_distance=self.MIN_LOOKAHEAD,
        )
        self._ui = ExtensionUI(self)
        self._ui.build_ui(self._model.get_lookahead_distance(), attachments=[])

        # If running inside the autogenerated startup test, quit the app so the test can complete.
        asyncio.ensure_future(self._request_quit_if_exttest())

    def on_shutdown(self):
        """Called when the extension is unloaded"""
        timeline = omni.timeline.get_timeline_interface()
        if timeline.is_playing():
            timeline.stop()

        self._clear_attachments()

        self._usd_listener = None
        self._stage_event_sub = None

        self._ui.teardown()
        self._ui = None
        self._model.teardown()
        self._model = None

    def _update_ui(self):
        self._ui.update_attachment_info(self._model.vehicle_to_curve_attachments.keys())

    def on_click_start_scenario(self):
        """On click event handler for starting the scenario"""

        async def start_scenario(model):
            timeline = omni.timeline.get_timeline_interface()
            if timeline.is_playing():
                timeline.stop()
                await omni.kit.app.get_app().next_update_async()
            lookahead_distance = self._ui.get_lookahead_distance()
            model.load_simulation(lookahead_distance)
            omni.timeline.get_timeline_interface().play()

        asyncio.ensure_future(start_scenario(self._model))

    def on_click_stop_scenario(self):
        """On click event handler for stopping the scenario"""

        async def stop_scenario():
            timeline = omni.timeline.get_timeline_interface()
            if timeline.is_playing():
                timeline.stop()
                await omni.kit.app.get_app().next_update_async()

        run_loop = asyncio.get_event_loop()
        asyncio.run_coroutine_threadsafe(stop_scenario(), loop=run_loop)

    def on_click_load_sample_vehicle(self):
        """On click event handler for loading a sample vehicle"""
        self._model.load_sample_vehicle()

    def on_click_load_ground_plane(self):
        """On click event handler for loading a ground plane"""
        self._model.load_ground_plane()

    def on_click_load_basis_curve(self):
        """On click event handler for loading a basis curve"""
        self._model.load_sample_track()

    def _on_click_load_forklift(self):
        self._model.load_forklift_rig()

    def on_click_attach_selected(self):
        """On click event handler for attaching selected prims to the vehicle"""
        selected_prim_paths = (
            omni.usd.get_context().get_selection().get_selected_prim_paths()
        )
        self._model.attach_selected_prims(selected_prim_paths)
        self._update_ui()

    def _clear_attachments(self):
        async def stop_scenario():
            timeline = omni.timeline.get_timeline_interface()
            if timeline.is_playing():
                timeline.stop()
                await omni.kit.app.get_app().next_update_async()

        run_loop = asyncio.get_event_loop()
        asyncio.run_coroutine_threadsafe(stop_scenario(), loop=run_loop)

        self._model.clear_attachments()
        self._update_ui()

    def on_click_clear_attachments(self):
        """On click event handler for clearing all attachments"""
        self._clear_attachments()

    def on_click_load_preset_scene(self):
        """On click event handler for loading a preset scene"""
        self._model.load_preset_scene()
        self._update_ui()

    def _on_stage_event(self, event: carb.events.IEvent):
        """Called on USD Context event"""
        if event.type == int(omni.usd.StageEventType.CLOSING):
            self._model.clear_attachments()
            self._update_ui()

    def _on_usd_change(self, objects_changed, _stage):
        carb.log_info("_on_usd_change")
        for resync_path in objects_changed.GetResyncedPaths():
            carb.log_info(resync_path)

    def on_changed_enabled_debug(self, model):
        """On change event handler for enabling/disabling debug mode"""
        self._model.set_enable_debug(model.as_bool)

    def on_lookahead_distance_changed(self, distance):
        """Called when the lookahead distance is changed"""
        clamped_lookahead_distance = self._model.update_lookahead_distance(distance)
        self._ui.set_lookahead_distance(clamped_lookahead_distance)

    def on_trajectory_loop_value_changed(self, widget_model):
        """Called when the trajectory loop value is changed"""
        self._model.set_close_trajectory_loop(widget_model.as_bool)

    def _on_steering_changed(self, model):
        self.on_click_stop_scenario()
        self._model.set_enable_rear_steering(model.as_bool)

    async def _request_quit_if_exttest(self):
        """If this is an extension startup test run, request Kit to quit."""
        try:
            carb.log_info("This is test run, requesting Kit App to quit...")
            print("This is test run, requesting Kit App to quit...")
            settings = carb.settings.get_settings()
            # Only act during test runs
            if not settings.get_as_bool("/app/isTestRun"):
                carb.log_info("[carb] Not a test run, skipping quit request.")
                print("Not a test run, skipping quit request.")
                return
            ext_test_id = settings.get_as_string("/exts/omni.kit.test/extTestId")
            print(f"Extension test ID: {ext_test_id}")

            # Match the autogenerated startup test for this extension
            if ext_test_id != "o2.vehicle.path_tracking-startup":
                print("Not a startup test for this extension, skipping quit request.")
                return
            # Allow a couple frames for initialization and log flushing

            app = omni.kit.app.get_app()
            for _ in range(2):
                await app.next_update_async()

            # Make shutdown deterministic and fast in test runs
            settings.set_bool("/app/fastShutdown", True)
            settings.set_bool("/app/file/ignoreUnsavedOnExit", True)
            settings.set_int("/app/quitAfter", 1)

            print("Requesting Kit App to quit...")
            # Use explicit exit code (0 = success) for compatibility
            app.post_quit(0)
            # Fallback: if still not quitting, try once more next frame
            await app.next_update_async()
            app.post_quit(0)
        except Exception as e:  # noqa: B902
            carb.log_warn(f"Failed to request quit during startup test: {e}")
