repos:
  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        name: isort (python)

  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v3.0.0a5  # Specify the desired Pylint version
    hooks:
      - id: pylint
        args:
          - "--output-format=colorized"
          - "--disable=too-few-public-methods, invalid-name, too-many-locals, too-many-arguments, too-many-instance-attributes"
          - --ignore-patterns=tools/packman/bootstrap/install_package.py,tools/scripts/link_app.py
        require_serial: true
        files: \.py$

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3.10

  - repo: https://github.com/pycqa/flake8
    rev: 7.2.0
    hooks:
      - id: flake8
        args: [--max-line-length=120]
