[package]
version = "1.0.3-beta"
title = "Vehicle Path Tracking Extension"
description="Allows omni.physxvehicle to move along a user-defined trajectory via path tracking 'pure pursuit' inspired algorithm."
readme  = "docs/index.rst"
changelog="docs/CHANGELOG.md"
repository = ""
icon = "data/icon.png"
preview_image="data/preview.png"
keywords = ["kit", "omni.physxvehicle", "animation", "path", "tracking", "vehicle"]

[dependencies]
"omni.usd" = {}
"omni.kit.uiapp" = {}
"omni.physx" = {}
"omni.physx.ui" = {}
"omni.physx.vehicle" = {}
"omni.usdphysics" = {}
"omni.physx.commands"  = {}
"omni.curve.creator" = {}
"omni.curve.manipulator" = {}
"o2.vehicle.pip_prebundle_extension" = {}

[[python.module]]
name = "o2.vehicle.path_tracking"

[[test]]
args = [
    "--/renderer/enabled=pxr",
    "--/renderer/active=pxr",
    "--/app/window/dpiScaleOverride=1.0",
    "--/app/window/scaleToMonitor=false",
    "--no-window"
]

dependencies = [
    "omni.hydra.pxr",
    "omni.kit.window.stage",
    "omni.kit.window.console"
]
